- name: Install VScode
  hosts: all
  become: true
  become_user: root
  tasks:
    - name: Dependencies installation
      apt:
        update_cache: true
        name:
          - wget
          - gpg
          - apt-transport-https
        state: latest

    - name: download gpg keys
      ansible.builtin.shell: wget -qO- https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor > packages.microsoft.gpg

    - name: install gpg key
      ansible.builtin.shell: sudo install -o root -g root -m 644 packages.microsoft.gpg /etc/apt/trusted.gpg.d/

    - name: add vscode gpg keys to sources.list.d
      ansible.builtin.shell: |
        sudo sh -c 'echo "deb [arch=amd64,arm64,armhf signed-by=/etc/apt/trusted.gpg.d/packages.microsoft.gpg] https://packages.microsoft.com/repos/code stable main" > /etc/apt/sources.list.d/vscode.list'
        rm -f packages.microsoft.gpg

    - name: update system and install code
      apt:
        update_cache: true
        name: code
        state: latest

    - name: install breaking packages
      apt:
        name:
          - libxshmfence1
          - libglu1

- name: install java8, java11
  hosts: all
  become: true
  become_user: root
  tasks:
    - name: installation of openjdk-8
      apt:
        name: openjdk-8-jdk
        install_recommends: true

    - name: installation of openjdk-11
      apt:
        name: openjdk-11-jdk
        install_recommends: true

- name: install python-is-python3
  hosts: all
  become: true
  become_user: root
  tasks:
    - name: installation of python-is-python3 package
      apt:
        name: python-is-python3
        state: latest

- name: storage solution
  hosts: all
  become: true
  become_user: root
  tasks:
    - name: install dropbox
      apt:
        deb: https://www.dropbox.com/download?dl=packages/ubuntu/dropbox_2020.03.04_amd64.deb

- name: generate openssh keypair with 4096bits RSA and fetch to local
  hosts: all
  become: true
  become_user: root
  tasks:
    - name: generation
      community.crypto.openssh_keypair:
        path: /home/ubuntu/.ssh/student_access

    - name: fetch to local
      ansible.builtin.fetch:
        src: /home/ubuntu/.ssh/student_access
        dest: ~/.ssh/student_access_keys

- name: GUI forwarding
  hosts: all
  become: yes
  become_user: root
  tasks:
    - name: setup X11 forwarding
      blockinfile:
        path: /etc/ssh/sshd_config
        block: |
          X11Forwarding true

    - name: install x11-apps
      apt:
        name: x11-apps
        state: latest

    - name: restart ssh service
      ansible.builtin.service:
        name: ssh
        state: restarted